version: '3'

services:
  postgresdb:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: "docker"
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-conf:/var/lib/postgresql/
    networks:
      postgres-network:
        ipv4_address: 172.50.50.105

  postgres11:
    container_name: postgres11
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: "docker"
    ports:
      - "15411:5432"
    volumes:
      - postgres11-data:/var/lib/postgresql/data
      - postgres11-conf:/var/lib/postgresql/
    networks:
      postgres-network:
        ipv4_address: 172.50.50.115

  pgadmin4:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "fabriciojf@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "docker"
    ports:
      - "16543:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgresdb
    networks:
      postgres-network:
        ipv4_address: 172.50.50.110

networks:
  postgres-network:
    external:
      name: devnetwork

volumes:
  postgres-data:
  postgres-conf:
  postgres11-data:
  postgres11-conf:
  pgadmin-data:
